notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: gUJWuBO1w6iEb9LmgAhfslKJcS3yj2hNH2t1EUzfEoT1ykM4MzMmQuQMeBGA2k20/7q7V9GFCyznegghPphNXXEMn9zsO3l3uyEJGazJrlWT5GzOeliLYU+gI+RYB1p6tkRbjBOJeyPkuC2PCnX+0dHEgeVWhLiS14g1u8+d/djTXDTVVPDeCTkl/kQ+J7UGpSOveMjueJc8hnneLWwtJFWee3kDLLj2YnNgIQzcO90cdFLTZf9/Tx0W0h15miRA/7zLDQtDrjZQdiCKKNrgVeLJW2Yt/BHhfGpsdwCOMR6BE9g4jP1rIMS+Aclw5+JxOiFRV7BK9KAdJYUz3QueVIHQCjDry3JDYQVuJyQ6wzfj3uM9UV31kixbBsSiTnYlMgSmuHeJHI9mlBHWppJEeY5s4PLLCX14i4dkWhDne5YIOT2dQU/5WwbRdJ29XZwzBg5CQR5n6sptpUGaDvb3uGXAKKg8EG10vOwXUr9P22uH4aHssKpLnpVU5aAYisnvOK8aLa/WxgE4DTkOutSGru0VvOgwwKm1tBXjPWsSoryY2l10sp5ik9l9fuvkhvKAz0eAShRKnLD6aI/vBVdamMk+ymg8hH7uq5da8kVNewcXV+eRrogwW+h3lhULdBslILmEsg/Hn53khxWMPe5Dev/UUq3dus2FZm6WaC3KJzQ=
  api_key:
    secure: iT3utC7vB/aB82zMc7ycRRDzg+TnIwmBLOoyhamsDJDQJCXMwkUKUaiWZwDR4NALb9jQ3w+n3qpGaRNui+d3XJq2Mitqtyl5FmJ6x7ioP5BJ23H4G2g7A7oa0ss7ITRueH9zAkEWaeNKReZTWjfy3mje4tmh702uhboWoZDfhi1dIq/9rVmQ2RDChyux9MmQAmy8aq1Y+hJpOje+7t50xJEOjL0fdlVqvDsRF+Wd7Rs/v3QYXiNn+MXGLRcx24CsHdve1ucN6kxoGJGKYgrzP8777M8UODVWfYZpL9KnquHVSA+Q5kHL6BU3gvELq4HMbg7HSdO1TTYtq6VEZ8Dijs8KAillOcIGGPZN/Dcw7JLIeT7DNvOYHVz1OQvq0xZIkX4OpuIYZaIwR3nTaaORq3t56DRde4QiErVhEeg79s+KNsIR+8kKNsG/LSfl7+cl5Gtjo9bq7PUyeEsHgFM9k/yQUXPYO0kLmUlGqGXURnLfGwHPGOtE0mUwuNW+WVQTzLyCubZpJP4p6c1hxaac828eA5SZZoMwEeRobDJBJCHV5Cq8O/pJlAUeaCd4gX2VRgHhEa5ed6GePkkfAkaU6SM16AV8lf/x5r59gvInq/XoXc84zlLihp9asVY+Ak6c26Lisv6W6cTH66rhAHNM5ssQVHYNns93gsbrSslaHT0=
  on:
    tags: true
